obj/alt_kill.o:  \
 /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/src/alt_kill.c \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/signal.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/signal.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/features.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/unistd.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/unistd.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_errno.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/os/alt_syscall.h
