obj/alt_main.o:  \
 /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/src/alt_main.c \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdio.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stdarg.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/stdio.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/string.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/fcntl.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/fcntl.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/stat.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/time.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/time.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/priv/alt_alarm.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/features.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdlib.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/stdlib.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/alloca.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/unistd.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/unistd.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  system_description/system.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_sys_init.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/priv/alt_legacy_irq.h \
  system_description/system.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/os/alt_hooks.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/priv/alt_file.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/os/alt_sem.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/priv/alt_no_error.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_log_printf.h \
  system_description/system.h
