obj/altera_avalon_timer_vars.o:  \
 /cygdrive/c/altera/11.1sp2/ip/altera/sopc_builder_ip/altera_avalon_timer/HAL/src/altera_avalon_timer_vars.c \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/string.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/sopc_builder_ip/altera_avalon_timer/HAL/inc/altera_avalon_timer.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  system_description/system.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /cygdrive/c/altera/11.1sp2/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_warning.h \
  /cygdrive/c/altera/11.1sp2/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h
