#!/bin/sh
#
# This file was automatically generated by the Nios II IDE Flash Programmer.
#
# It will be overwritten when the flash programmer options change.
#

cd E:/AA_IO_BD/new/TFT_SD_for24TFT/lcd_at_nios_qii_part/software/lcd/Debug

# Creating .flash file for the FPGA configuration
"$SOPC_KIT_NIOS2/bin/sof2flash" --epcs --input="E:/AA_IO_BD/new/TFT_SD_for24TFT/lcd_at_nios_qii_part/lcd_at_nios.sof" --output="lcd_at_nios.flash" 

# Programming flash with the FPGA configuration
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x03001800 --sidp=0x03002068 --id=0 --timestamp=1429273175  "lcd_at_nios.flash"

# Creating .flash file for the project
"$SOPC_KIT_NIOS2/bin/elf2flash" --epcs --after="lcd_at_nios.flash" --input="lcd.elf" --output="epcs.flash"

# Programming flash with the project
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x03001800 --sidp=0x03002068 --id=0 --timestamp=1429273175  "epcs.flash"

