obj/alt_irq_handler.o:  \
 /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/src/alt_irq_handler.c \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  system_description/system.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/priv/alt_legacy_irq.h \
  system_description/system.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/os/alt_hooks.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h
