obj/altera_avalon_jtag_uart_init.o:  \
 /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/HAL/src/altera_avalon_jtag_uart_init.c \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/string.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/fcntl.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/fcntl.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/stat.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/time.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/time.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/priv/alt_alarm.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/features.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/d/altera/11.0/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/limits.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/priv/alt_legacy_irq.h \
  system_description/system.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/ioctl.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/inc/altera_avalon_jtag_uart_regs.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/io.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/HAL/inc/altera_avalon_jtag_uart.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /cygdrive/d/altera/11.0/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_warning.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/os/alt_sem.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/priv/alt_no_error.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/os/alt_flag.h \
  /cygdrive/d/altera/11.0/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/HAL/inc/altera_avalon_jtag_uart_fd.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  system_description/system.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/d/altera/11.0/nios2eds/components/altera_hal/HAL/inc/sys/alt_log_printf.h \
  system_description/system.h
